/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * Cat Facts API
 * OpenAPI spec version: 1.0
 */

/**
 * Breed
 */
export interface Breed {
	/** Breed */
	breed?: string;
	/** Country */
	country?: string;
	/** Origin */
	origin?: string;
	/** Coat */
	coat?: string;
	/** Pattern */
	pattern?: string;
}
