/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * Cat Facts API
 * OpenAPI spec version: 1.0
 */

/**
 * CatFact
 */
export interface CatFact {
	/** Fact */
	fact?: string;
	/** Length */
	length?: number;
}
