/**
 * Generated by orval v6.11.0 🍺
 * Do not edit manually.
 * Maintenance Insights Service
 * Maintenance Insighs Service provides analytical insights about maintenance events
 * OpenAPI spec version: 1.0.0
 */
import type { EventItemDetailed } from './eventItemDetailed';
import type { ComparedDurationTreeNode } from './comparedDurationTreeNode';
import type { Measures } from './measures';

/**
 * Two compared events
 */
export interface ComparisonResponse {
	base?: EventItemDetailed;
	comparison: ComparedDurationTreeNode[];
	description?: string;
	descriptionHTML?: string;
	measures: Measures;
	target?: EventItemDetailed;
}
