/**
 * Generated by orval v6.11.0 🍺
 * Do not edit manually.
 * Maintenance Insights Service
 * Maintenance Insighs Service provides analytical insights about maintenance events
 * OpenAPI spec version: 1.0.0
 */
import type { TemporalAttribute } from './temporalAttribute';
import type { NodeDisplayName } from './nodeDisplayName';
import type { Duration } from './duration';
import type { NodeId } from './nodeId';

/**
 * Event duration tree with two temporal attributes and comparison information
 */
export interface ComparedDurationTreeNode {
	baseTemporalAttribute: TemporalAttribute;
	/** Long description of the node (to be shown on tooltip hover-box) */
	description?: string;
	/** Long description of the node, formatted as HTML */
	descriptionHTML?: string;
	displayName: NodeDisplayName;
	/** Change of duration from base (absolute) */
	durationChange?: Duration;
	/** Relative change of duration from base (rate) */
	durationChangeRate?: Duration;
	id: NodeId;
	includes?: ComparedDurationTreeNode[];
	self?: string;
	targetTemporalAttribute: TemporalAttribute;
}
