/**
 * Generated by orval v6.11.0 🍺
 * Do not edit manually.
 * Maintenance Insights Service
 * Maintenance Insighs Service provides analytical insights about maintenance events
 * OpenAPI spec version: 1.0.0
 */

/**
 * Excel export file
 */
export interface CutoverExportOutput {
	/** Base64 encoded string of the excel export */
	content?: string;
}
