/**
 * Generated by orval v6.11.0 🍺
 * Do not edit manually.
 * Maintenance Insights Service
 * Maintenance Insighs Service provides analytical insights about maintenance events
 * OpenAPI spec version: 1.0.0
 */

/**
 * Document format (xml or html)
 */
export type DocumentFormat = (typeof DocumentFormat)[keyof typeof DocumentFormat];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DocumentFormat = {
	xml: 'xml',
	html: 'html',
} as const;
