/**
 * Generated by orval v6.11.0 🍺
 * Do not edit manually.
 * Maintenance Insights Service
 * Maintenance Insighs Service provides analytical insights about maintenance events
 * OpenAPI spec version: 1.0.0
 */
import type { DocumentItem } from './documentItem';

/**
 * List of analytical documents
 */
export type DocumentsCollection = DocumentItem[];
