/**
 * Generated by orval v6.11.0 🍺
 * Do not edit manually.
 * Maintenance Insights Service
 * Maintenance Insighs Service provides analytical insights about maintenance events
 * OpenAPI spec version: 1.0.0
 */

export interface DocumentItem {
	/** Description of document type */
	description?: string;
	/** Display name of the document */
	displayName: string;
	/** Technical name of the document */
	id: string;
	/** Link to a document resource */
	self: string;
}
