/**
 * Generated by orval v6.11.0 🍺
 * Do not edit manually.
 * Maintenance Insights Service
 * Maintenance Insighs Service provides analytical insights about maintenance events
 * OpenAPI spec version: 1.0.0
 */
import type { NodeDisplayName } from './nodeDisplayName';
import type { ElementsObject } from './elementsObject';
import type { NodeId } from './nodeId';
import type { PhaseRuntimeItem } from './phaseRuntimeItem';
import type { _Link } from './_link';
import type { TemporalAttribute } from './temporalAttribute';
import type { NodeType } from './nodeType';

/**
 * Event duration tree node
 */
export interface DurationTreeNode {
	/** Long description of the node (to be shown on tooltip hover-box) */
	description: string;
	/** Long description of the node, formatted as HTML */
	descriptionHTML?: string;
	displayName: NodeDisplayName;
	/** Link to elements (if available) */
	elements?: ElementsObject;
	id: NodeId;
	/** The level of the node in the duration tree
	 */
	level?: number;
	/** The order of the node in the duration tree in the same level
	 */
	order?: number;
	/** The parent of the node
	 */
	parent?: string;
	/** List of phases for this node (if available) */
	phases?: PhaseRuntimeItem[];
	self?: string;
	/** Link to statements (if available) */
	statements?: _Link;
	temporalAttribute: TemporalAttribute;
	/** The global order of the node in the duration tree
	 */
	traversalOrder?: number;
	type?: NodeType;
}
