/**
 * Generated by orval v6.11.0 🍺
 * Do not edit manually.
 * Maintenance Insights Service
 * Maintenance Insighs Service provides analytical insights about maintenance events
 * OpenAPI spec version: 1.0.0
 */
import type { NodeDisplayName } from './nodeDisplayName';
import type { ElementsObject } from './elementsObject';
import type { NodeId } from './nodeId';
import type { _Link } from './_link';
import type { TemporalAttribute } from './temporalAttribute';

/**
 * Event duration tree
 */
export interface DurationTreeDeep {
	/** Long description of the node (to be shown on tooltip hover-box) */
	description: string;
	/** Long description of the node, formatted as HTML */
	descriptionHTML?: string;
	displayName: NodeDisplayName;
	/** Link to elements (if available) */
	elements?: ElementsObject;
	id: NodeId;
	includes?: DurationTreeDeep[];
	self?: string;
	/** Link to statements (if available) */
	statements?: _Link;
	temporalAttribute: TemporalAttribute;
}
