/**
 * Generated by orval v6.11.0 🍺
 * Do not edit manually.
 * Maintenance Insights Service
 * Maintenance Insighs Service provides analytical insights about maintenance events
 * OpenAPI spec version: 1.0.0
 */

/**
 * Object with element type name and its link
 */
export interface ElementTypeObject {
	description?: string;
	descriptionHTML?: string;
	displayName?: string;
	id?: string;
	self?: string;
}
