/**
 * Generated by orval v6.11.0 🍺
 * Do not edit manually.
 * Maintenance Insights Service
 * Maintenance Insighs Service provides analytical insights about maintenance events
 * OpenAPI spec version: 1.0.0
 */
import type { HistogramChart } from './histogramChart';
import type { ElementType } from './elementType';
import type { ElementTypes } from './elementTypes';

/**
 * Histogram of elements in process
 */
export interface ElementsResponseHistogram {
	data: HistogramChart;
	type?: ElementType;
	types?: ElementTypes;
}
