/**
 * Generated by orval v6.11.0 🍺
 * Do not edit manually.
 * Maintenance Insights Service
 * Maintenance Insighs Service provides analytical insights about maintenance events
 * OpenAPI spec version: 1.0.0
 */
import type { ElementItemList } from './elementItemList';
import type { Measures } from './measures';
import type { _Link } from './_link';
import type { ElementType } from './elementType';
import type { ElementTypes } from './elementTypes';

/**
 * Element collection response in items format
 */
export interface ElementsCollectionResponse {
	data: ElementItemList;
	measures: Measures;
	next?: _Link;
	/** Total number of elements found with filter applied.
This property can be used to show the total number of items found,
before you actually fetch all items using pagination.
 */
	size?: number;
	type?: ElementType;
	types?: ElementTypes;
}
