/**
 * Generated by orval v6.11.0 🍺
 * Do not edit manually.
 * Maintenance Insights Service
 * Maintenance Insighs Service provides analytical insights about maintenance events
 * OpenAPI spec version: 1.0.0
 */
import type { _Link } from './_link';

/**
 * Link to elements and the default type
 */
export interface ElementsObject {
	defaultType?: string;
	self?: _Link;
}
