/**
 * Generated by orval v6.11.0 🍺
 * Do not edit manually.
 * Maintenance Insights Service
 * Maintenance Insighs Service provides analytical insights about maintenance events
 * OpenAPI spec version: 1.0.0
 */
import type { EventList } from './eventList';
import type { Measures } from './measures';
import type { _Link } from './_link';

/**
 * List of events matching the search criteria
 */
export interface EventCollectionResponse {
	data: EventList;
	measures: Measures;
	next?: _Link;
	/** Total number of events found with filter applied.
This property can be used to show the total number of items found,
before you actually fetch all items using pagination.
 */
	size?: number;
}
