/**
 * Generated by orval v6.11.0 🍺
 * Do not edit manually.
 * Maintenance Insights Service
 * Maintenance Insighs Service provides analytical insights about maintenance events
 * OpenAPI spec version: 1.0.0
 */
import type { EventAttributes } from './eventAttributes';
import type { EventItemDetailedDurationTree } from './eventItemDetailedDurationTree';
import type { _Link } from './_link';
import type { EventType } from './eventType';

/**
 * Event object
 */
export interface EventItemDetailed {
	attributes?: EventAttributes;
	durationTree?: EventItemDetailedDurationTree;
	self?: string;
	/** Optional link available simulations for the current event */
	simulations?: _Link;
	title?: string;
	type?: EventType;
}
