/**
 * Generated by orval v6.11.0 🍺
 * Do not edit manually.
 * Maintenance Insights Service
 * Maintenance Insighs Service provides analytical insights about maintenance events
 * OpenAPI spec version: 1.0.0
 */

/**
 * Event type
 */
export type EventType = (typeof EventType)[keyof typeof EventType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EventType = {
	Upgrade: 'Upgrade',
	'S/4HANA_Conversion': 'S/4HANA Conversion',
	Update: 'Update',
} as const;
