/**
 * Generated by orval v6.11.0 🍺
 * Do not edit manually.
 * Maintenance Insights Service
 * Maintenance Insighs Service provides analytical insights about maintenance events
 * OpenAPI spec version: 1.0.0
 */
import type { EventViewDescriptor } from './eventViewDescriptor';

/**
 * List of views available for a given event. The first item in the list is the default view
 */
export type EventViews = EventViewDescriptor[];
