/**
 * Generated by orval v6.11.0 🍺
 * Do not edit manually.
 * Maintenance Insights Service
 * Maintenance Insighs Service provides analytical insights about maintenance events
 * OpenAPI spec version: 1.0.0
 */

/**
 * Event view descriptor
 */
export interface EventViewDescriptor {
	/** Description of the view */
	description?: string;
	/** Display name of the view */
	displayName?: string;
	/** Link to a view object */
	self?: string;
}
