/**
 * Generated by orval v6.11.0 🍺
 * Do not edit manually.
 * Maintenance Insights Service
 * Maintenance Insighs Service provides analytical insights about maintenance events
 * OpenAPI spec version: 1.0.0
 */

/**
 * Timestamp, point in time following ISO 8601 with time zone specifier (local time or UTC)
 */
export interface ExtendedTimestamp {
	formatted?: string;
	value?: number;
}
