/**
 * Generated by orval v6.11.0 🍺
 * Do not edit manually.
 * Maintenance Insights Service
 * Maintenance Insighs Service provides analytical insights about maintenance events
 * OpenAPI spec version: 1.0.0
 */

/**
 * Filter collection according to given criteria.

Grammar
-------

filter = expression [ connector expression ] ;

connector = "," | ";" ;

expression = field operator value ;

operator = "==" | "<>" | ">" | "<" | ">=" | "<=" | "*=" | "!=";

fields for events = "sid" | "host" | "instnr" | "start_date" | "end_date" | "type" | 'id' | "run_type" | "system_type"

fields for elements = "start_date" | "end_date" | "name" | "type" | "runtime"

value = string ;

Example:

sid==ABC,sid==CDE;instNr==123456;start_date>2019-01-12;type==S/4HANA Conversion,type==Upgrade

Translated to SQL:

(sid==ABC OR:sid==CDE) AND instNr=='123456' AND start_date>'2\;019-01-12\' AND (TYPE==S4CONVERSION OR TYPE==UPGRADE)

Explanation: return items having sid equal to ABC or sid equal to CDE. All results must
have instNr equal to 123456. All results must have start_date later than "2019-01-12". All results must have type of either "S/4HANA Conversion" or "Upgrade"

Connector "," groups expressions with "OR" logic.
Connector ";" groups expressions with "AND" logic.
OR connector have precedence over AND connector.

 */
export type FilterExpression = string;
