/**
 * Generated by orval v6.11.0 🍺
 * Do not edit manually.
 * Maintenance Insights Service
 * Maintenance Insighs Service provides analytical insights about maintenance events
 * OpenAPI spec version: 1.0.0
 */
import type { Duration } from './duration';
import type { TemporalAttribute } from './temporalAttribute';

/**
 * List of durations
 */
export interface FlatDurationNode {
	/** Name of the duration node */
	displayName: string;
	/** Estimated value */
	duration?: Duration;
	/** Change of duration from base (absolute) */
	duration_change?: Duration;
	/** Relative change of duration from base (rate) */
	duration_change_rate?: Duration;
	/** Unique node identifier */
	id: string;
	/** Id of the parent node */
	parent?: string;
	/** Estimated value */
	temporalAttribute?: TemporalAttribute;
}
