/**
 * Generated by orval v6.11.0 🍺
 * Do not edit manually.
 * Maintenance Insights Service
 * Maintenance Insighs Service provides analytical insights about maintenance events
 * OpenAPI spec version: 1.0.0
 */
import type { FlatDurationNode } from './flatDurationNode';

/**
 * Duration object as a flat list
 */
export interface FlatDurationTree {
	/** Name of the duration node */
	displayName: string;
	/** The ID of the duration tree */
	id?: string;
	/** List of duration nodes */
	nodes: FlatDurationNode[];
}
