/**
 * Generated by orval v6.11.0 🍺
 * Do not edit manually.
 * Maintenance Insights Service
 * Maintenance Insighs Service provides analytical insights about maintenance events
 * OpenAPI spec version: 1.0.0
 */
import type { ExtendedTimestamp } from './extendedTimestamp';

export interface HistogramBin {
	/** End of the bin */
	binEnd: ExtendedTimestamp;
	/** Start of the bin */
	binStart: ExtendedTimestamp;
	/** Number of elements in the bin */
	count: number;
}
