/**
 * Generated by orval v6.11.0 🍺
 * Do not edit manually.
 * Maintenance Insights Service
 * Maintenance Insighs Service provides analytical insights about maintenance events
 * OpenAPI spec version: 1.0.0
 */

/**
 * The desired number of bins of a histogram.
This argument is alternative to _step_width_ (only one is allowed)
All running processes will be split into the bins.

 */
export type HistogramBins = number;
