/**
 * Generated by orval v6.11.0 🍺
 * Do not edit manually.
 * Maintenance Insights Service
 * Maintenance Insighs Service provides analytical insights about maintenance events
 * OpenAPI spec version: 1.0.0
 */
import type { InputParameterType } from './inputParameterType';

export interface InputParameter {
	/** Description of the parameter */
	description?: string;
	/** Type of the parameter */
	type?: InputParameterType;
}
