/**
 * Generated by orval v6.11.0 🍺
 * Do not edit manually.
 * Maintenance Insights Service
 * Maintenance Insighs Service provides analytical insights about maintenance events
 * OpenAPI spec version: 1.0.0
 */

/**
 * Limit number of items in result set. Result set size can be equal or less then
specified number. If the total result set is larger than possible to return
with given maxResult, the link to next page of results is provided.

If _next_ page link is present in reply, the result set is incomplete.
Called can use this link to retrive next portion of result.

 */
export type MaxResult = number;
