/**
 * Generated by orval v6.11.0 🍺
 * Do not edit manually.
 * Maintenance Insights Service
 * Maintenance Insighs Service provides analytical insights about maintenance events
 * OpenAPI spec version: 1.0.0
 */
import type { MeasureDescriptor } from './measureDescriptor';

/**
 * Map of measures
 */
export interface Measures {
	default?: MeasureDescriptor;
	[key: string]: MeasureDescriptor;
}
