/**
 * Generated by orval v6.11.0 🍺
 * Do not edit manually.
 * Maintenance Insights Service
 * Maintenance Insighs Service provides analytical insights about maintenance events
 * OpenAPI spec version: 1.0.0
 */

export interface MeasureItem {
	/** Human friendly representation of the value */
	formatted: string;
	/** The value of the measure */
	value: number;
}
