/**
 * Generated by orval v6.11.0 🍺
 * Do not edit manually.
 * Maintenance Insights Service
 * Maintenance Insighs Service provides analytical insights about maintenance events
 * OpenAPI spec version: 1.0.0
 */

/**
 * Limit result to items with duration is longer than specified.
Duration is in seconds.
Durations for results, which are shorter than specified threshold are collapsed
(sum) into pseudo element with the name 'Others'.
This element is added to the result set if _minDuration_ attribute is specified.

 */
export type MinDuration = number;
