/**
 * Generated by orval v6.11.0 🍺
 * Do not edit manually.
 * Maintenance Insights Service
 * Maintenance Insighs Service provides analytical insights about maintenance events
 * OpenAPI spec version: 1.0.0
 */
import type { FilterExpression } from './filterExpression';
import type { MaxResult } from './maxResult';
import type { PageToken } from './pageToken';
import type { OrderBy } from './orderBy';
import type { ComparisonInfo } from './comparisonInfo';

export type MisApiEventsEventsGetCollectionParams = {
	filter?: FilterExpression;
	max_result?: MaxResult;
	page_token?: PageToken;
	order_by?: OrderBy;
	comparison_base?: ComparisonInfo;
};
