/**
 * Generated by orval v6.11.0 🍺
 * Do not edit manually.
 * Maintenance Insights Service
 * Maintenance Insighs Service provides analytical insights about maintenance events
 * OpenAPI spec version: 1.0.0
 */
import type { MinDuration } from './minDuration';
import type { MaxResult } from './maxResult';
import type { FilterExpression } from './filterExpression';
import type { PageToken } from './pageToken';
import type { OrderBy } from './orderBy';

export type MisApiElementsItemsGetElementsItemsParams = {
	min_duration?: MinDuration;
	max_result?: MaxResult;
	filter?: FilterExpression;
	page_token?: PageToken;
	order_by?: OrderBy;
};
