/**
 * Generated by orval v6.11.0 🍺
 * Do not edit manually.
 * Maintenance Insights Service
 * Maintenance Insighs Service provides analytical insights about maintenance events
 * OpenAPI spec version: 1.0.0
 */

export type MisApiEventsEventsGetItemFormat =
	(typeof MisApiEventsEventsGetItemFormat)[keyof typeof MisApiEventsEventsGetItemFormat];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MisApiEventsEventsGetItemFormat = {
	flat: 'flat',
	deep: 'deep',
} as const;
