/**
 * Generated by orval v6.11.0 🍺
 * Do not edit manually.
 * Maintenance Insights Service
 * Maintenance Insighs Service provides analytical insights about maintenance events
 * OpenAPI spec version: 1.0.0
 */

/**
 * The type of the node in a cutover node list

 */
export type NodeType = (typeof NodeType)[keyof typeof NodeType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const NodeType = {
	fixedDuration: 'fixedDuration',
	databaseDuration: 'databaseDuration',
	timestamp: 'timestamp',
} as const;
