/**
 * Generated by orval v6.11.0 🍺
 * Do not edit manually.
 * Maintenance Insights Service
 * Maintenance Insighs Service provides analytical insights about maintenance events
 * OpenAPI spec version: 1.0.0
 */
import type { StatementImportance } from './statementImportance';
import type { StatementItem } from './statementItem';

/**
 * Messages (check results, recommendations) for a given node
 */
export interface NodeStatements {
	/** Maximal importance of messages in the statement list */
	maxImportance: StatementImportance;
	/** List of statements for a current node */
	statementList: StatementItem[];
}
