/**
 * Generated by orval v6.11.0 🍺
 * Do not edit manually.
 * Maintenance Insights Service
 * Maintenance Insighs Service provides analytical insights about maintenance events
 * OpenAPI spec version: 1.0.0
 */

/**
 * Sort result along fields.

_orderBy_ term consists of field name and optionally tag 'desc' indicating reverse sorting
(from large to little).  Per default sorting order is ascending (from little to large).

Grammar:
--------

order_expression = order_term { "," order_term } ;

order_term = field { " " [ "desc" ] } ;

field = "sid" | "host" | "instnr" | "start_date" | "end_date" | "type" | 'id' ;

See specific list of supported filter terms in the description of
the corresponding endpoint.

Example:

sid, start_date desc

 */
export type OrderBy = string;
