/**
 * Generated by orval v6.11.0 🍺
 * Do not edit manually.
 * Maintenance Insights Service
 * Maintenance Insighs Service provides analytical insights about maintenance events
 * OpenAPI spec version: 1.0.0
 */

/**
 * Limit result set to a specific page. Used for paged navigation though result sets.

Page tokens expire after 24 hours. Caller must repeat initial query to collection
to obtain fresh page token. It is not possible to change maxResult, filter or sorting
order of results during pagination (initial values set by first query of the
collection remained applied).

Specification of pageToken and maxResult, "filter" or "order_by" parameters
in the same query is not allowed. Same query parameters remain effective for next pages.

 */
export type PageToken = string;
