/**
 * Generated by orval v6.11.0 🍺
 * Do not edit manually.
 * Maintenance Insights Service
 * Maintenance Insighs Service provides analytical insights about maintenance events
 * OpenAPI spec version: 1.0.0
 */
import type { Host } from './host';
import type { Instnr } from './instnr';
import type { Product } from './product';
import type { RunType } from './runType';
import type { Sid } from './sid';
import type { SystemType } from './systemType';

/**
 * Permament system information
 */
export interface PermanentSystemInformation {
	host: Host;
	instnr: Instnr;
	product?: Product;
	runType: RunType;
	sid: Sid;
	systemType: SystemType;
}
