/**
 * Generated by orval v6.11.0 🍺
 * Do not edit manually.
 * Maintenance Insights Service
 * Maintenance Insighs Service provides analytical insights about maintenance events
 * OpenAPI spec version: 1.0.0
 */
import type { MeasureItem } from './measureItem';
import type { Stage } from './stage';

/**
 * One phase item
 */
export interface PhaseRuntimeItem {
	/** Describes how long the phase took to complete */
	duration?: MeasureItem;
	/** The id of the phase */
	id?: string;
	stage?: Stage;
}
