/**
 * Generated by orval v6.11.0 🍺
 * Do not edit manually.
 * Maintenance Insights Service
 * Maintenance Insighs Service provides analytical insights about maintenance events
 * OpenAPI spec version: 1.0.0
 */

/**
 * The type of the maintenance event.
Can be Go-Live (real) or an upgrade of a sandbox system (test).

 */
export type RunType = (typeof RunType)[keyof typeof RunType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RunType = {
	'Go-Live': 'Go-Live',
	Sandbox: 'Sandbox',
} as const;
