/**
 * Generated by orval v6.11.0 🍺
 * Do not edit manually.
 * Maintenance Insights Service
 * Maintenance Insighs Service provides analytical insights about maintenance events
 * OpenAPI spec version: 1.0.0
 */
import type { SimulationDescriptorInputParameters } from './simulationDescriptorInputParameters';
import type { InputParameter } from './inputParameter';

export interface SimulationDescriptor {
	/** Descriptiton of the simulation in Markdown */
	description: string;
	/** Long description of the node, formatted as HTML */
	descriptionHTML?: string;
	/** Simulation display name */
	displayName: string;
	/** Technical name of the simulation (ID) used for referencing it in API */
	id: string;
	/** List of simulation IDs which are not compatible with this simulation. */
	incompatibleSimulations: string[];
	inputParameters?: SimulationDescriptorInputParameters;
	orderedInputParameters?: InputParameter[];
}
