/**
 * Generated by orval v6.11.0 🍺
 * Do not edit manually.
 * Maintenance Insights Service
 * Maintenance Insighs Service provides analytical insights about maintenance events
 * OpenAPI spec version: 1.0.0
 */

export type SimulationResultForecastItemAllOf = {
	/** Formatted string about the selected simulations */
	selected_simulations?: string;
	/** Formatted bullet points with hints */
	simulation_hints?: string;
};
