/**
 * Generated by orval v6.11.0 🍺
 * Do not edit manually.
 * Maintenance Insights Service
 * Maintenance Insighs Service provides analytical insights about maintenance events
 * OpenAPI spec version: 1.0.0
 */
import type { FlatDurationTree } from './flatDurationTree';
import type { SimulationResultForecastItem } from './simulationResultForecastItem';
import type { Measures } from './measures';

/**
 * Simulation result
 */
export interface SimulationResult {
	base?: FlatDurationTree;
	/** Simulation forecasts. The first element is the conservative forecast and the second element is the optimistic forecast */
	forecast?: SimulationResultForecastItem[];
	measures?: Measures;
}
