/**
 * Generated by orval v6.11.0 🍺
 * Do not edit manually.
 * Maintenance Insights Service
 * Maintenance Insighs Service provides analytical insights about maintenance events
 * OpenAPI spec version: 1.0.0
 */

/**
 * Phase stage
 */
export type Stage = (typeof Stage)[keyof typeof Stage];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Stage = {
	source: 'source',
	target: 'target',
	any: 'any',
} as const;
