/**
 * Generated by orval v6.11.0 🍺
 * Do not edit manually.
 * Maintenance Insights Service
 * Maintenance Insighs Service provides analytical insights about maintenance events
 * OpenAPI spec version: 1.0.0
 */

/**
 * Importance of the analytical statement (info, warning, critical)
 */
export type StatementImportance = (typeof StatementImportance)[keyof typeof StatementImportance];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const StatementImportance = {
	INFO: 'INFO',
	WARNING: 'WARNING',
	CRITICAL: 'CRITICAL',
} as const;
