/**
 * Generated by orval v6.11.0 🍺
 * Do not edit manually.
 * Maintenance Insights Service
 * Maintenance Insighs Service provides analytical insights about maintenance events
 * OpenAPI spec version: 1.0.0
 */
import type { StatementImportance } from './statementImportance';

/**
 * Message item
 */
export interface StatementItem {
	/** Name of the check which produces the statement */
	_stmtId: string;
	importance: StatementImportance;
	/** Text of the statement in Markdown format */
	text: string;
	/** Text of the statment in HTML format */
	textHTML?: string;
}
