/**
 * Generated by orval v6.11.0 🍺
 * Do not edit manually.
 * Maintenance Insights Service
 * Maintenance Insighs Service provides analytical insights about maintenance events
 * OpenAPI spec version: 1.0.0
 */

/**
 * The system type, which undergoes a maintenance event.
Can be development, quality or productive system. Should be one of these values: Production,
Development, Quality, EARLYWATCH, Maintenance Insights Service Upload

 */
export type SystemType = string;
