/**
 * Generated by orval v6.11.0 🍺
 * Do not edit manually.
 * Maintenance Insights Service
 * Maintenance Insighs Service provides analytical insights about maintenance events
 * OpenAPI spec version: 1.0.0
 */

/**
 * Types of change
 */
export type TemporalPosition = (typeof TemporalPosition)[keyof typeof TemporalPosition];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TemporalPosition = {
	before: 'before',
	after: 'after',
} as const;
