/**
 * Generated by orval v6.11.0 🍺
 * Do not edit manually.
 * Maintenance Insights Service
 * Maintenance Insighs Service provides analytical insights about maintenance events
 * OpenAPI spec version: 1.0.0
 */
import type { UploadResultItemType } from './uploadResultItemType';

/**
 * One item of the upload result, represents one file
 */
export interface UploadResultItem {
	description?: string;
	descriptionHTML?: string;
	document_id?: string;
	filename: string;
	size?: number;
	status: string;
	type?: UploadResultItemType;
}
