/**
 * Generated by orval v6.11.0 🍺
 * Do not edit manually.
 * Maintenance Insights Service
 * Maintenance Insighs Service provides analytical insights about maintenance events
 * OpenAPI spec version: 1.0.0
 */

/**
 * Upload information
 */
export interface UploadDescription {
	/** Longer text description of available options for file upload. Formatted in markdown. */
	description?: string;
	/** Longer text description of available options for file upload. Formatted in HTML. */
	descriptionHTML?: string;
	/** Short text of available upload file formats. */
	displayName?: string;
}
