/**
 * Generated by orval v6.11.0 🍺
 * Do not edit manually.
 * Maintenance Insights Service
 * Maintenance Insighs Service provides analytical insights about maintenance events
 * OpenAPI spec version: 1.0.0
 */

/**
 * Types of allowed XML files
 */
export type UploadResultItemType = (typeof UploadResultItemType)[keyof typeof UploadResultItemType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UploadResultItemType = {
	APPLANA: 'APPLANA',
	UPGANA: 'UPGANA',
} as const;
