/**
 * Generated by orval v6.11.0 🍺
 * Do not edit manually.
 * Maintenance Insights Service
 * Maintenance Insighs Service provides analytical insights about maintenance events
 * OpenAPI spec version: 1.0.0
 */

/**
 * Type of the value
 */
export type ValueType = (typeof ValueType)[keyof typeof ValueType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ValueType = {
	string: 'string',
	integer: 'integer',
} as const;
