/**
 * Generated by orval v6.11.0 🍺
 * Do not edit manually.
 * Maintenance Insights Service
 * Maintenance Insighs Service provides analytical insights about maintenance events
 * OpenAPI spec version: 1.0.0
 */
import type { Version } from './version';
import type { DbSize } from './dbSize';
import type { DbType } from './dbType';
import type { TemporalPosition } from './temporalPosition';
import type { ExtendedTimestamp } from './extendedTimestamp';

/**
 * Volatile system data
 */
export interface VolatileSystemInformation {
	basisRelease: Version;
	dbSize: DbSize;
	dbType: DbType;
	temporalPosition: TemporalPosition;
	timestamp: ExtendedTimestamp;
}
